u_training_mean: -0.06929559429949586
u_training_std: 0.1358005549716049
v_training_mean: -0.0323937796117541
v_training_std: 0.08899177232117582
mag_mean: 0.1446947511640557

gpu_to_use: 0

# === training ===
retrain_mode: False
model_to_retrain: ""

partial_conv_mode: False

training_mode: True
testSeed: 0
epochs: 1
batch_size: 100  #use ~80 for server
lr: 0.001

standardizer_type: zscore
                  # zscore
                  # maxmag
                  # units

noise_function: div_free
              # gaussian
              # div_free
              # div_gaussian
              # hh_decomp_div_free
              # cached_div

loss_function: mse
              # mse
              # physical
              # best_loss
w1: 0.6
w2: 0.4
num_workers: 0

# === Both ===
noise_steps: 100
min_beta: 0.0001
max_beta: 0.02

# === inpainting ===
inpainting_batch_size: 1
num_images_to_process: 5
n_samples: 1
resample_nums: [1]
save_pt_fields: True

# === div-free inpainting ===
use_comb_net: auto
              #yes
              #no
              #auto
comb_training_steps: 200
weight_strategy: pcgrad
fidelity_weight: 1
physics_weight: 1
save_combination_data: False # warning: True may use a large amount of storage

model_paths:
  - "../../models/div_free_model.pt"