u_training_mean: -0.0692955942994962
u_training_std: 0.13580055497160493
v_training_mean: -0.032393779611754124
v_training_std: 0.08899177232117583

testSeed: 0
n_epochs: 2
batch_size: 35
lr: 0.001

loss_function: physical
noise_function: gaussian
w1: 0.5
w2: 0.5

n_steps: 1000
min_beta: 0.0001
max_beta: 0.02
training_mode: True
inpainting_batch_size: 1

image_counter: 0
num_images_to_process: 5
n_samples: 1

model_path: "./"