u_training_mean: -0.0692955942994962
u_training_std: 0.13580055497160493
v_training_mean: -0.032393779611754124
v_training_std: 0.08899177232117583
gpu_to_use: 0

testSeed: 0
n_epochs: 2
batch_size: 35
lr: 0.001

standardizer_type: zscore
noise_function: gaussian
loss_function: mse
w1: 0.5
w2: 0.5
num_workers: 0
max_size: 50

n_steps: 100
min_beta: 0.0001
max_beta: 0.02
training_mode: True
inpainting_batch_size: 1

num_images_to_process: 5
n_samples: 1
resample_nums: [5]

model_path: "../trained_models/ddpm_ocean_model_Jun17_1000.pt"