u_training_mean: 3.709986267835613e-16
u_training_std: 0.7045390679430601
v_training_mean: 1.4372364157421022e-19
v_training_std: 0.7096627835167776
gpu_to_use: 0

retrain_mode: False
model_to_retrain: ""

training_mode: True
testSeed: 0
n_epochs: 20
batch_size: 35
lr: 0.001

standardizer_type: maxmag
noise_function: hh_decomp_div_free
loss_function: mse
w1: 0.5
w2: 0.5
num_workers: 0

n_steps: 100
min_beta: 0.0001
max_beta: 0.02
inpainting_batch_size: 1
num_images_to_process: 1
n_samples: 1
resample_nums: [5]

model_path: "../../ddpm_ocean_model_best_checkpoint.pt"