u_training_mean: -0.0692955942994962
u_training_std: 0.13580055497160493
v_training_mean: -0.032393779611754124
v_training_std: 0.08899177232117583

testSeed: 0
n_epochs: 2
batch_size: 35
lr: 0.001
loss_function: mse
noise_function: gaussian

n_steps: 1000
min_beta: 0.0001
max_beta: 0.02
training_mode: True
inpainting_batch_size: 1

snapshots: 10
model_path: "../trained_models/ddpm_ocean_v0_2025_JUN_4.pt"