u_training_mean: -0.06929559429949586
u_training_std: 0.1358005549716049
v_training_mean: -0.0323937796117541
v_training_std: 0.08899177232117582
gpu_to_use: 0

# === training ===
retrain_mode: False
model_to_retrain: ""

partial_conv_mode: False

training_mode: True
testSeed: 0
epochs: 2000
batch_size: 100  #use ~80 for server
lr: 0.001

standardizer_type: zscore
                  # zscore
                  # maxmag
                  # units

noise_function: gaussian
              # gaussian
              # div_free
              # div_gaussian
              # hh_decomp_div_free
              # cached_div

loss_function: mse
              # mse
              # physical
w1: 0.5
w2: 0.5
num_workers: 0

# === Both ===
noise_steps: 700
min_beta: 0.0001
max_beta: 0.02

# === inpainting ===
inpainting_batch_size: 1
num_images_to_process: 1
n_samples: 1
resample_nums: [5]
save_pt_fields: False

model_paths:
  - "../trained_models/weekend_ddpm_ocean_model.pt"
