# Div-free model with unified z-score standardization
# This preserves the divergence-free property during training

u_training_mean: -0.06929559429949586
u_training_std: 0.1358005549716049
v_training_mean: -0.0323937796117541
v_training_std: 0.08899177232117582
mag_mean: 0.1446947511640557

# Unified statistics (required for zscore_unified)
shared_mean: -0.05084468695562498
shared_std: 0.11479844598042026

gpu_to_use: 0
retrain_mode: true
model_to_retrain: '/Users/caleyjb/Library/Mobile Documents/com~apple~CloudDocs/JeffsStuff/PLU/Research/diffusionInpaintingVectorFields/ddpm/training/training_output/div_free_unified_zscore/ddpm_ocean_model_best_checkpoint.pt'
partial_conv_mode: false
training_mode: true
testSeed: 0
epochs: 100
batch_size: 128
lr: 0.0005

# KEY: Use unified z-score to preserve div-free property
standardizer_type: zscore_unified

# Div-free noise
noise_function: div_free

loss_function: mse
w1: 0.6
w2: 0.4
num_workers: 0
noise_steps: 100
min_beta: 0.0001
max_beta: 0.02
inpainting_batch_size: 1
num_images_to_process: 1
n_samples: 1
resample_nums:
- 5
save_pt_fields: false
model_paths:
