u_training_mean: -0.06929559429949586
u_training_std: 0.1358005549716049
v_training_mean: -0.0323937796117541
v_training_std: 0.08899177232117582
mag_mean: 0.1446947511640557
gpu_to_use: 0
retrain_mode: false
model_to_retrain: ''
partial_conv_mode: false
training_mode: true
testSeed: 0
epochs: 2000
batch_size: 100
lr: 0.001
standardizer_type: zscore
noise_function: gaussian
loss_function: best_loss
w1: 0.0
w2: 1.0
num_workers: 0
noise_steps: 100
min_beta: 0.0001
max_beta: 0.02
inpainting_batch_size: 1
num_images_to_process: 1
n_samples: 1
resample_nums:
- 5
save_pt_fields: false
model_paths:
- ../trained_models/weekend_ddpm_ocean_model.pt
